language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t eguziy/frontend .

script:
  - docker run -e CI=true eguziy/frontend npm run test -- --coverage